### ISSUE TITLE
Request for Implementation of Step and Impulse Response Functions

### ISSUE THREAD

**Issue by hackhubafrica** [python-control/python-control#1048]
### Summary
The `control` library currently lacks implementations for the step and impulse response functions. These functions are essential for control system analysis and simulation, allowing users to analyze the behavior of systems to standard input signals.

### Proposed Functions
1. **Step Response**: A function to calculate the step response of a transfer function. The step response indicates how a system reacts to a step input.
2. **Impulse Response**: A function to calculate the impulse response of a transfer function. The impulse response provides insights into the system's dynamics in response to an instantaneous input.

### Implementation
I propose the following implementations for these functions:

#### Custom Step and Impulse Function
```python
def custom_step(numerator, denominator, t):
    # Implementation details here
    pass  # Replace with actual implementation

def custom_impulse(numerator, denominator, t):
    # Implementation details here
    pass  # Replace with actual implementation

**Comment by murrayrm** [comment]
These functions already exist: `step_response` and `impulse_response` accept a transfer function object and generate a response that can then be plotted.  Try this:
```
import control as ct
sys = ct.tf([1], [1, 2, 1])
ct.step_response(sys).plot(label="step response")
ct.impulse_response(sys).plot(label="impulse response")
```
