### ISSUE TITLE
AttributeError: module 'control' has no attribute 'LinearIOSystem'

### ISSUE THREAD

**Issue by IvoVanBaren** [python-control/python-control#1060]
Hello,

A call to LinearIOSystem in [fbs2e-python](https://github.com/murrayrm/fbs2e-python/tree/main)
/figure-1.18-airfuel_selectors.py fails with message: AttributeError: module 'control' has no attribute 'LinearIOSystem'

How can I get around this failure.

**Comment by slivingston** [comment]
The minimal change is to replace both instances of `LinearIOSystem` with `StateSpace`.

I will send a pull request to <https://github.com/murrayrm/fbs2e-python>, but for now, other code in that repository may need similar updates given https://github.com/python-control/python-control/pull/916

**Comment by murrayrm** [comment]
I've updated [murrayrm/fbs2e-python](https://github.com/murrayrm/fbs2e-python) to be compatible with control-0.10.1 and fixed this issue.
