### ISSUE TITLE
Can't compute forced response of a discrete system

### ISSUE THREAD

**Issue by cacunas** [python-control/python-control#113]
I've tried to plot the forced response, impulse response, or step response of a sampled (discrete) system, and so far it has been impossible for me. In the attachment is one of the codes that I've tried to do so. I'll be very grateful if someone can review the issue, and point out if is something wrong with the current implementation of python-control or simply an error in my code. Apologies in advance if this is the wrong place to put this; but I couldn't find anywhere else to put it. And thanks for this great package.
[t1.txt](https://github.com/python-control/python-control/files/486171/t1.txt)

**Comment by roryyorke** [comment]
If the forced_response inputs have sample rate that matches your discretized model, it seems to work; this script (I've made the plant stable, and removed the Sympy bits):
```python
import control as ctl
import control.matlab as ml
import numpy as np
import matplotlib.pyplot as plt

j = np.complex(0,1)
a = -7+j*np.sqrt(51)
b = np.conjugate(a)

# Sistema en contínuo
sys1c_num, sys1c_den = ml.zpk2tf([], [-.5, a, b], [-100])
sys1c = ctl.TransferFunction(sys1c_num, sys1c_den)
Tc, y1c = ctl.impulse_response(sys1c)
plt.plot(Tc, y1c, label='continuous');

# Sistema Discreto

dt = 0.001
sys1d = ctl.sample_system(sys1c, dt, method='zoh')

td = np.arange(0.,Tc[-1]+dt,dt);
u1d = np.zeros(td.shape);
u1d[0] = 1/dt # seems to correspond to a continuous time impulse

Td, y1d, _ = ctl.forced_response(sys1d, td, u1d, 0)
plt.plot(Td, y1d, label='discrete, input step 1ms');

# try with 1s sample rate

dts = 1
tds = np.arange(0.,Tc[-1]+dts,dts);
u1ds = np.zeros(tds.shape);
u1ds[0] = 1/dts

Tds, y1ds, x1ds = ctl.forced_response(sys1d, tds, u1ds, 0)
print('tds.shape',tds.shape,
      'u1ds.shape',u1ds.shape,
      'Tds.shape',Tds.shape,
      'y1ds.shape',y1ds.shape,
      'x1ds.shape',x1ds.shape)

assert td.shape[0] == y1ds.shape[0]
plt.plot(td,y1ds,label='discrete, input step 1s')
plt.legend()
plt.show()
```
gives 
![t1](https://cloud.githubusercontent.com/assets/110974/18761185/3fbb09ca-8104-11e6-83d9-27a4f2d40808.png)

and output
```
tds.shape (15,) u1ds.shape (15,) Tds.shape (15,) y1ds.shape (14001, 1) x1ds.shape (14001, 3)
```

I'm not familiar with ```forced_response```, but I'd expect the output time array (```Tds```, here) to have shape matching the response (```y1ds```), so in my opinion this is a bug.
