### ISSUE TITLE
how to pzplot AR model results

### ISSUE THREAD

**Issue by Fankbai** [python-control/python-control#155]
I've posted this question on 'statsmodels' library [#3885](https://github.com/statsmodels/statsmodels/issues/3885) , but it still * does not work out.*

the matlab code work well:
```matlab
> n = ar(data, 4)
> % get the coefficiants
> A = n.a                    % as the denominator
> B = 1                        % as the nominator
> sysInput = tf(A, B)    % as the sys typycal
> pzplot(sysInput)
```
followed this idea, I try this using python-control:

```python
>> A = mdl.params
>> B= 1  
>> ipt = control.tf(A,B)
>> pzmap(ipt)
>> plt.show()
```

it seems work, but figures display:
**MATLAB**
![ed](https://user-images.githubusercontent.com/10338671/29740976-cb40caae-8a52-11e7-80b5-b0b881e323a0.png)
**Python** 
![2017-08-26_072002](https://user-images.githubusercontent.com/10338671/29740983-dc13f2a2-8a52-11e7-99fd-8ced5fac3036.png)

**Comment by Fankbai** [comment]
I've solve it using function provided  by [Christopher Felton ](https://www.dsprelated.com/showcode/244.php)  instead of control.pzmap().

but what's wrong with control.pzmap()?

**Comment by roryyorke** [comment]
pzmap seems fine to me.  In  the original Matlab example, the denominator is 1, so there should be no poles.

```python
%matplotlib inline
from control import tf, pzmap
```

```python
z = tf([1, 0], [1], -1)
g1 = z / (z ** 2 - 2 * 0.5 * 0.9 * z + 0.9 ** 2)
g2 = z / (z ** 2 - 2 * 0.2 * 0.4 * z + 0.4 ** 2)
g = g1 * g2
display(g)
```

$$\frac{z^2}{z^4 - 1.06 z^3 + 1.114 z^2 - 0.2736 z + 0.1296}$$

```python
pzmap(g);
```

![output_2_0](https://user-images.githubusercontent.com/110974/89116637-9ea4ba00-d496-11ea-816b-4b226390df96.png)
