### ISSUE TITLE
extra file "statesp.py+"

### ISSUE THREAD

**Issue by roryyorke** [python-control/python-control#184]
presumably a typo at save-time

https://github.com/python-control/python-control/blob/1801c9a4850bb82b4a3d350570440f9c4893c691/control/statesp.py%2B

The only hassle is checking that whatever changes were made there have been saved to statesp.py

**Comment by murrayrm** [comment]
Oops.  I'll delete from master next time I'm committing things.

**Comment by murrayrm** [comment]
Fixed in commit 28204cc.
