### ISSUE TITLE
Add Project to the Python Package Index [sf#3]

### ISSUE THREAD

**Issue by murrayrm** [python-control/python-control#19]
**Reported by eike on 2011-06-12 13:43 UTC**
The Python Control project should be added to the Python Package Index. 
http://pypi.python.org/pypi

This would ease some administrative work:

* Uploading packages can be easily automated. 
* Each package has a documentation website. Uploading the the generated website can be automated too.
* Users can install the library with ``easy_install``. A user would only need to type ``easy_install python-control`` to download and install the package. 
* It would also give the project additional visibility.

An introduction how to automate build and upload tasks, in conjunction with the Python Package Index, is here:
http://packages.python.org/an_example_pypi_project/

**Comment by cwrowley** [comment]
I just uploaded 0.7.0 to PyPI (and binstar).
