### ISSUE TITLE
ImportError: cannot import name mixsyn

### ISSUE THREAD

**Issue by Robomate** [python-control/python-control#207]
```
    from control import tf, ss, mixsyn, feedback, step_response
ImportError: cannot import name mixsyn
```

**Comment by roryyorke** [comment]
mixsyn will be in python-control 0.8.0.  If you want to try it so long, you can use the development version of python-control, but then you'll also need the development version of Slycot; unfortunately, Slycot can be tricky to setup, especially on Windows.

This issue can be closed.
