### ISSUE TITLE
evalfr does not behave as expected [sf#6]

### ISSUE THREAD

**Issue by murrayrm** [python-control/python-control#22]
**Reported by *anonymous on 2013-05-24 14:32 UTC**
The current implementation of evalfr is different from the matlab function evalfr. Could you please "fix" it.

Example: Evaluate the transfer function G=tf(1,[2,3,4]) at s=1+2j

In Matlab one would type evalfr(G,s) and get the expectet result (0.0051-0.0711j).
Using this module typing evalfr(G,s) will actually compute evalfr(G,s*j) which is (0.09756098+0.12195122j), that is, it evaluated G at the point -2+j instead.

I agree that this is what one would expect (after reading the documentation of evalfr) but I would rather have a behavior that conforms with matlab (after all the module control.matlab was designed to emulate matlab's routines)

Thanks,

Juan C. Cockburn
juan.cockburn@rit.edu

**Comment by murrayrm** [comment]
In looking through the code, it appears that this issue is still open and not yet addressed.  Updating milestone to 0.8.0 since it should be fixed for that release.

**Comment by murrayrm** [comment]
Another possible approach to handling this:

* Define the `__call__` method in `TransferFunction` to allow `G(s)` to return the value of the transfer function `G` at the complex number `s`.

* Remove the `evalfr` method from `TransferFunction`, `StateSpace`, and `FRD` classes since this functionality is present through `__call__`.

* Optionally remove the `evalfr` _function_ in `lti.py`.  (I'm not sure if this removal is useful since `lti.evalfr()` currently acts in the same way as the MATLAB `evalfr` function => no confusion likely.)

* Define the `evalfr` _function_ in the MATLAB module to behave in the same way as MATLAB's `evalfr` function.

This approach would get rid of the current inconsistency in the code and also avoid anyone who is using `{TransferFunction, StateSpace, FRD}.evalfr` from having a bug suddenly appear due to a change in the way `evalfr` is handled.  The rationale for removing the `evalfr` _function_ in `lti.py` is to encourage the use of of `G(s)` for transfer functions (seems more elegant) or `sys.freqresp(omega)` for any LTI system.

**Comment by cwrowley** [comment]
I like all of these ideas: using the `__call__` method for `TransferFunction` objects, removing the `evalfr` methods, and moving the `evalfr` function to the MATLAB module.  Though it may be more polite to keep the `evalfr` routines for a little while and give a deprecation warning, just so anybody using this doesn't find their code suddenly broken without warning.

**Comment by murrayrm** [comment]
The fixes described above have (roughly) been implemented in PR #179.  The main difference from what we discussed is that I left in the old `evalfr` method functionality, but renamed it to `_evalfr`, since it was being used by `margins.py` and `frdata.py` in what seemed like sensible ways.  See PR #179 for more details on the changes.

**Comment by murrayrm** [comment]
Addressed in PR #179
