### ISSUE TITLE
Update conda-forge recipe to use 

### ISSUE THREAD

**Issue by murrayrm** [python-control/python-control#222]
While releasing v0.8.0 on conda-forge, I got the following warning:
```
This project is currently running on CircleCI 1.0 which will no longer be supported after 
August 31, 2018. Please start migrating this project to CircleCI 2.0.
```
Not sure what we need to change (or where, but probably [conda-forge/control-feedstock](https://github.com/conda-forge/control-feedstock)), but flagging this here for now.

**Comment by moorepants** [comment]
Probably just needed a rerender: https://conda-forge.org/docs/conda_smithy.html

**Comment by moorepants** [comment]
0.8.0 is now on conda forge: https://github.com/conda-forge/control-feedstock/pull/3
