### ISSUE TITLE
Documentation note

### ISSUE THREAD

**Issue by matangk** [python-control/python-control#227]
Am I terribly confused? when defining "Transfer function", documentation say:
"where n is generally greater than or equal to m (for a proper transfer function)"
Isn't it the other way around?

http://python-control.readthedocs.io/en/latest/conventions.html

Thanks ahead.

**Comment by murrayrm** [comment]
Yup, it's backwards.  I think it will make the most sense to use n for the denominator (since n is the usual variable for the number of states).  Marking this as a bug to fix.

**Comment by murrayrm** [comment]
This is fixed in the current master (checked on readthedocs).
