### ISSUE TITLE
Giving a description to the toolbox

### ISSUE THREAD

**Issue by don4get** [python-control/python-control#271]
Hello! 

@murrayrm Can you add a description and a link to the documentation website, on the following page, please?
https://github.com/python-control/python-control
![image](https://user-images.githubusercontent.com/22080415/50788994-3cd09e00-12bb-11e9-9705-449a5c66d177.png)

 
Something like:
```Control toolbox in python: State space or transfer function representation, control design (Robust control, LQR), analysis through Bode / Nyquist / Nichols plots and even more!```

Just below this description, you can also specify topics:
![image](https://user-images.githubusercontent.com/22080415/50789063-76090e00-12bb-11e9-9cd1-8b178708ce26.png)

It will help the library gain visibility through key words search :) 

In the future, we can think about other features to help the community grow, as described on this page:
https://github.com/python-control/python-control/community
![image](https://user-images.githubusercontent.com/22080415/50789151-b49ec880-12bb-11e9-8d29-e3db6f8cb76f.png)

**Comment by murrayrm** [comment]
Done.  Added the first line of the README (which we can change, of course).  The URL redirects to the readthedocs page (which we can also change, of course).
