### ISSUE TITLE
The sisotool function was renamed to controlSystemDesigner in Matlab R2015a

### ISSUE THREAD

**Issue by billtubbs** [python-control/python-control#328]
See [Mathworks release notes](https://www.mathworks.com/help/control/release-notes.html?searchHighlight=sisotool&s_tid=doc_srchtitle).

> Using sisotool to open SISO Design Tool does not generate an error in this release, but the function might be removed in a future release.

This might not be a big deal but thought I would raise it.  Assuming it was only the name that was changed shall we just add an alias for the controlSystemDesigner name?

**Comment by murrayrm** [comment]
MATLAB's Control System Designer seems to be quite a bit more powerful than what is currently implemented in `sisotool`.  From the web page, it supports:

* Interactive Bode, root locus, and Nichols graphical editors for adding, modifying, and removing controller poles, zeros, and gains.
* Automated PID, LQG, or IMC tuning.
* Optimization-based tuning (requires Simulink Design Optimization™ software).
* Automated loop shaping (requires Robust Control Toolbox™ software).

All `sisotool` does at this point is let you click on the root locus plot to change the loop gain.

Having said all of that, It would be fine to just add a line at the end of `sisotool.py` to allow `controlSystemDesigner` to run `sisotool`.

**Comment by billtubbs** [comment]
I see.  Well in that case if our `sisotool` is more like the 'old' MATLAB sisotool and people recognize it as that we should probably keep the name the same.  Feel free to close this issue.

**Comment by billtubbs** [comment]
When I was looking at sisotool I was thinking, "this would be much better as a class object than a function".  Maybe we go down that route later and then change the name to `ControlSystemDesigner` and make it more like a fully-functional app in a window.

**Comment by murrayrm** [comment]
Looks like this issue is effective resolved: leave `sisotool` since that matches the current functionality.
