### ISSUE TITLE
Upload docs to pythonhosted / pypi

### ISSUE THREAD

**Issue by jgoppert** [python-control/python-control#33]
Pypi now has a place to host docs for python packages. It would be good to upload our docs there.

You can now host documentation at http://pythonhosted.org/control. To upload documentation, prepare a .zip file that is unpacked into this URL. Only static pages are supported. The zip file must have a top-level "index.html".

**Comment by cwrowley** [comment]
Version 0.7.0 is now available at http://python-control.readthedocs.org
