### ISSUE TITLE
Can't install control in Travis-CI

### ISSUE THREAD

**Issue by kdavies4** [python-control/python-control#37]
I have a package that depends on `control` but I have trouble testing it in Travis-CI due to the following error when running `pip install control`:

> ImportError: Unable to import git_revision. Try removing control/version.py and the build directory before building.

The full log is here: https://travis-ci.org/kdavies4/ModelicaRes/jobs/35359894.

Do you know how to fix this? It seems that `control.version` can't be imported until the `control` package is installed, which requires `control.version`. A catch-22?

**Comment by cwrowley** [comment]
This seems to work now that 0.7.0 is up on PyPI.  Note that you can now install slycot with conda too, as follows:
```
conda config --add channels http://conda.binstar.org/cwrowley
conda install slycot
conda install control
```
