### ISSUE TITLE
Wrong step response for transfer function

### ISSUE THREAD

**Issue by brilliant-ember** [python-control/python-control#387]
Python produces wrong step response for the transfer function shown in the image. The expected (correct) step response is shown in both Mathmatica and MatLab, the step response should oscillate since there're complex poles, however, python plots a wrong step resp, and finds wrong poles for the system.
PS. both octave and python suffer from the same issue.

Figure 1. Wrong python step response
![image](https://user-images.githubusercontent.com/23269759/78245551-a850ed80-74b5-11ea-96bb-cd30486e4922.png)

Figure 2 Correct step response by MatLab
![image](https://user-images.githubusercontent.com/23269759/78245512-98390e00-74b5-11ea-90f8-557d6e7bfd3a.png)

Figure 3 Correct Step response by mathmatica
![image](https://user-images.githubusercontent.com/23269759/78245619-c9194300-74b5-11ea-8130-6ec873f36f70.png)

Figure 4 wrong poles calculated by python
![image](https://user-images.githubusercontent.com/23269759/78245670-dd5d4000-74b5-11ea-964d-ea3481c5b156.png)

**Comment by josujugo** [comment]
Hi, Mohamed:

You should revise the parameters in the definition of the transfer function in python. it's 0.1 not 0.01. I have checked in python and works correctly.

![image](https://user-images.githubusercontent.com/47331920/78246848-19aa9380-74ea-11ea-9296-ef71f9b842cb.png)
