### ISSUE TITLE
tf2ss() returns incorrect result

### ISSUE THREAD

**Issue by chimnonvuive** [python-control/python-control#396]
I checked the code. It seems that the problem relates to the function `td04ad` in `slycot` but I am not familiar with the language.

![screen02](https://user-images.githubusercontent.com/36569441/81081976-d1cdc080-8f1c-11ea-819b-eb8ab55a0c6e.jpg)

**Comment by bnavigator** [comment]
Why do you think the result is incorrect? Both state space systems are equivalent, just a different representation.

**Comment by chimnonvuive** [comment]
> Why do you think the result is incorrect? Both state space systems are equivalent, just a different representation.

Is there any

**Comment by bnavigator** [comment]
If you don't have Slycot, it would be a call to `scipy.signal.tf2ss()`

https://github.com/python-control/python-control/blob/6b24bb42a8da5b15cb79699e74fb33b30ba7935a/control/statesp.py#L984

With Slycot it is a call to `TD04AD()`
https://github.com/python-control/python-control/blob/6b24bb42a8da5b15cb79699e74fb33b30ba7935a/control/statesp.py#L959-L960

Which is documented in the source:
https://github.com/python-control/Slycot/blob/c8d3a2143c6e0091db4801f2ee68f0d256537f2f/slycot/src/TD04AD.f#L175-L219

**Comment by chimnonvuive** [comment]
> If you don't have Slycot, it would be a call to `scipy.signal.tf2ss()`
> 
> https://github.com/python-control/python-control/blob/6b24bb42a8da5b15cb79699e74fb33b30ba7935a/control/statesp.py#L984
> 
> With Slycot it is a call to `TD04AD()`
> https://github.com/python-control/python-control/blob/6b24bb42a8da5b15cb79699e74fb33b30ba7935a/control/statesp.py#L959-L960
> 
> Which is documented in the source:
> https://github.com/python-control/Slycot/blob/c8d3a2143c6e0091db4801f2ee68f0d256537f2f/slycot/src/TD04AD.f#L175-L219

Thank you for your generous help! I will close the issue now.
