### ISSUE TITLE
Add user manual to python-control distribution tarball

### ISSUE THREAD

**Issue by murrayrm** [python-control/python-control#40]
Suggestions received via e-mail:

> On 2 Nov 2014, at 4:57 , Ralph Koettlitz <e-mail removed> wrote:
>
> Hello,
> would you be so kind to put the manual into the archive of Python Control? 
>
> Regards 
> R. Koettlitz

It seems like it would be useful for people downloading the tarball from SourceForge to have some sort of user manual that is part of the distribution (without needing to compile).  Need to look into how other distributions handle this and then decide how to proceed.

**Comment by cwrowley** [comment]
Closing this issue, since the docs are now up on [readthedocs](https://python-control.readthedocs.org).
