### ISSUE TITLE
Vehicle Steering Example, observer design

### ISSUE THREAD

**Issue by oayan** [python-control/python-control#409]
Hi,

I have been going through the vehicle steering example and have the following question:
In "Eigenvalue placement observer design":
`# Create a linear model of the lateral dynamics driving the estimator
est = ct.StateSpace(A - L @ C, np.block([[B, L]]), np.eye(2), np.zeros((2,2)))`

Where do the second and the third terms in the arguments come from? According to the book, the differential equation of the estimation is characterized as:
d\hat{x} / dt = _A_ \hat{x} + **_B_**_u_ + **_L_**(_y_ - **_C_** \hat{x})

It justifies the first A - LC but the second term, i.e., `np.block([[B, L]])`, is a 2x2 matrix. And also **_C_** can not be a 2 by 2 matrix, since _y_ is a scalar in the given example.

**Comment by murrayrm** [comment]
The estimator has two inputs: _u_ and _y_.  The first input needs to be multiplied by _B_ to be added to the estimated state and the second input needs to be multiplied by _L_.

The output of the estimator of is the estimated state of the system, and hence the _C_ matrix for the estimator is the identity matrix.
