### ISSUE TITLE
rlocus

### ISSUE THREAD

**Issue by im-AMS** [python-control/python-control#411]
Hii thanks for the module..

```
from control.matlab import *

s = tf('s')
g=1/(s*(s+4)*(s**2+4*s+20))

rlocus(g)
```

i dont get any output..
is there a way to show the output something like show() or something

**Comment by murrayrm** [comment]
The following will do what you want:
```
from control.matlab import *
import matplotlib.pyplot as plt   

s = tf('s')
g=1/(s*(s+4)*(s**2+4*s+20))

rlocus(g)
plt.show()
```

If that doesn't work, reopen this issue and let us know what version of Python and `python-control` you are using.
