### ISSUE TITLE
Labeled LTI systems

### ISSUE THREAD

**Issue by aarondewindt** [python-control/python-control#510]
From what I can find it is currently not possible to label LTI systems. What I mean is giving inputs, outputs and states names and possibly units. Are there future plans for this? How much interest is there for such a feature? Or did I miss something?

**Comment by bnavigator** [comment]
Not units, but the iosys module supports naming inputs, outputs and states. Try https://python-[control.iosys.LinearIOSystem](control.readthedocs.io/en/0.8.4/generated/control.iosys.LinearIOSystem.html)

**Comment by aarondewindt** [comment]
@bnavigator Awesome, that should do, Thanks.
