### ISSUE TITLE
old sourceforge page out of date

### ISSUE THREAD

**Issue by sawyerbfuller** [python-control/python-control#545]
The old sourceforge page https://sourceforge.net/projects/python-control/ is out of date:
* There is no indication there that the project has moved to github, at least on the home page. 
* File downloads only go up to version 0.7. 
* Download and install instructions are out of date there. 
* There appear to be many downloads from there still, 29 of version 0.7 this week.

**Comment by murrayrm** [comment]
Updated SourceForge page with information on where to go to get the latest version (http://python-control.org, which redirects to ReadTheDocs, and here).
