### ISSUE TITLE
control.forced_response argument T

### ISSUE THREAD

**Issue by forgi86** [python-control/python-control#586]
In version 0.9:

* For a discrete-time system , the time vector should be optional in the forced response (as stated in the documentation). 
However, this code does not work for me:

sys = control.drss(states=1, outputs=1, inputs=1)
u = np.random.randn(1000)
control.forced_response(sys, U=u)

* Also, the default value of return_x is stated to be True in the docstring, but it is  None (False?) in the code.

**Comment by bnavigator** [comment]
> * For a discrete-time system , the time vector should be optional in the forced response (as stated in the documentation).

Automatic timevector calculation only works if the sys has `dt` specified. Should be stated more explicitly in the documentation and a better error message should be provided.

Plus, there is a bug in `drss`. It should return a system with `dt=True`, but the returned system has `dt=0`.
 
> * Also, the default value of return_x is stated to be True in the docstring, but it is  None (False?) in the code.

Agreed, this is a bug.
