### ISSUE TITLE
squeeze: return shape of the frequency response.

### ISSUE THREAD

**Issue by bnavigator** [python-control/python-control#594]
Something strange about the return shape of the frequency response. For a square 2x2 system:

```
sys(np.array(0.0), squeeze=False).shape
(2, 2, 1)

sys(0.0, squeeze=False).shape
(2, 2)
```

_Originally posted with the wrong result mapping by @forgi86 in https://github.com/python-control/python-control/issues/593#issuecomment-808929799_

**Comment by bnavigator** [comment]
BTW, omega has to be complex.

```
>>> import numpy as np
>>> from control import rss
>>> sys = rss(2,2,2)
>>> sys(np.array(0.0j), squeeze=False).shape
(2, 2, 1)
>>> sys(0.0j, squeeze=False).shape
(2, 2)
```

Now I am even more confused and will stop for this Sunday evening.

**Comment by murrayrm** [comment]
I think this behavior is expected.  If you call an LTI system with a list of frequencies, you get back a list of responses.

**Comment by murrayrm** [comment]
Sorry, accidently closed.

**Comment by forgi86** [comment]
@bnavigator as far as I can see looks like you can pass real/complex/imaginary argument. I would expect the output to be the Laplace/Z transform for ct/dt in general, but haven't really tested!
