### ISSUE TITLE
Control doesn't linearize when working with scalars.

### ISSUE THREAD

**Issue by Kreijstal** [python-control/python-control#614]
say we have

```
io_s = ct.iosys.NonlinearIOSystem(lambda t,x,u:x**2+u, None, states=1)
io_s.linearize(2,-4)
```
Returns https://github.com/python-control/python-control/blob/e81f648431e2a9f2cdf583702522bc2af0e1c360/control/iosys.py#L2003
It seems it expects vectors which is why it doesn't work.

**Comment by bnavigator** [comment]
The [documentation](https://python-control.readthedocs.io/en/0.9.0/generated/control.NonlinearIOSystem.html) explicitly states that  `updfcn` and `outfcn` work with 1D arrays.

In your example, how is the algorithm supposed to know, that `u` is a scalar?

```pycon
>>> import control as ct
>>> io_s = ct.iosys.NonlinearIOSystem(lambda t,x,u:x**2+u, None, states=1)
>>> io_s.noutputs
1
>>> io_s.ninputs
>>> type(io_s.ninputs)
<class 'NoneType'>
```

This works:

```pycon
>>> import control as ct
>>> io_s = ct.iosys.NonlinearIOSystem(updfcn=lambda t, x, u, param=None: x**2+u,
...                                   outfcn=None, inputs=1, outputs=1, states=1)
>>> linio_s = io_s.linearize(2, -4)
>>> linio_s.output(0,1,2)
array([1.])
```
