### ISSUE TITLE
bode_plot does not show a plot

### ISSUE THREAD

**Issue by erichstuder** [python-control/python-control#618]
bode_plot seems not to plot in any case.
The example on https://python-control.readthedocs.io/en/0.9.0/generated/control.bode_plot.html does not show a plot.

It seems that the plot is shown if matplotlib.pyplot.show() is called afterwards.
But from my point of view this seems like an ugly workaround.

Is this a bug?

**Comment by bnavigator** [comment]
> It seems that the plot is shown if matplotlib.pyplot.show() is called afterwards.

Behavior depends on your console environment.

https://matplotlib.org/stable/tutorials/introductory/usage.html#what-is-interactive-mode

This is outside of the scope of python-control
