### ISSUE TITLE
Is there any option for input delay?

### ISSUE THREAD

**Issue by chimnonvuive** [python-control/python-control#626]
I tried `exp` function in numpy but it does not work. What I expect is for example, in MATLAB:
`>> tf(1, [1 2], 'InputDelay', 2)`
Is there any option or workaround? Thanks

**Comment by murrayrm** [comment]
Systems with pure time delay haven't been implemented yet.  If you are interested in contributing this functionality, that would be great.  See issue #238 for some related comments.

A possible work around is to use a Pade approximation (using the `pade` function).
