### ISSUE TITLE
forced_response           ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by franciscotovarmit** [python-control/python-control#644]
So I followed the forced_response example and putted the code sequences into one file .
When I compile with python I get this error result:

    (t, y, x) = control.forced_response(H, t, u, X0=0)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by murrayrm** [comment]
The forced_response function  returns t and y. If you want x (states), add return_x=True.
