### ISSUE TITLE
Result of the damp function for discrete time systems

### ISSUE THREAD

**Issue by vincentchoqueuse** [python-control/python-control#646]
Hi, 

This is my first contribution on GitHub ;)

### Problem 

The method `damp()` seems to return a wrong result for discrete systems with negative poles

```
import control as ctl
H = ctl.tf([1],[1,0.2],1)
H.damp()
```

Result : RuntimeWarning: invalid value encountered in log

### Investigation

The problem seems to come from the type of the `poles` variable in the `damp`method of the LTI object

```
if isdtime(self, strict=True):
     splane_poles = np.log(poles)/self.dt
else:
      splane_poles = poles
wn = absolute(splane_poles)
Z = -real(splane_poles)/wn
return wn, Z, poles
```

### Solution

The `poles` variable must be cast to a numpy complex type as follows

```
if isdtime(self, strict=True)
      splane_poles = np.log(poles.astype(complex))/self.dt
...
```

**Comment by bnavigator** [comment]
Hi,

thanks for catching this!

> This is my first contribution on GitHub ;)

Awesome! Would you try to make the next step and create a [Pull Request](https://github.com/python-control/python-control/wiki/How-to-contribute-with-a-pull-request) with your proposed changes?

Bonus points for adding your example to `test_damp()` (using `pytest.mark.parametrize()`) :

https://github.com/python-control/python-control/blob/6b7a9c78f16ab04e009be7155308294080d8a5d1/control/tests/lti_test.py#L54-L71
