### ISSUE TITLE
Discrete system bode_plot nyquist line does not respect Hz parameter

### ISSUE THREAD

**Issue by dc5048** [python-control/python-control#650]
https://github.com/python-control/python-control/blob/18976c1eabe56a6f9afe0aadea6679024b84b335/control/freqplot.py#L332

This line should be:
`omega_nyq_line = np.array((np.nan, nyquistfrq_plot, nyquistfrq_plot))`

... so that the nyquist limit will be plotted in Hz when requested.  Currently the nyquist limit always plots as rad/s, even if the Hz argument is True.

**Comment by bnavigator** [comment]
Closed by #651
