### ISSUE TITLE
Incorrect Escaping in Function Reference Documentation

### ISSUE THREAD

**Issue by cleichner** [python-control/python-control#655]
It looks like the end of this comment didn't make it into the docs

<img width="764" alt="Screen Shot 2021-09-19 at 12 25 46 PM" src="https://user-images.githubusercontent.com/769380/133940360-bb1f6c62-342e-415d-a40b-0c6cf6595bf6.png">

**Comment by bnavigator** [comment]
Thank you for flagging this @cleichner!

**Comment by cleichner** [comment]
Thanks for doing the work!
