### ISSUE TITLE
H-infinity norm computation

### ISSUE THREAD

**Issue by florentdimeglio** [python-control/python-control#707]
Hi! 

Do you think it would be possible to release a function that simply computes the H-infinity norm of a MIMO transfer function? 

Thanks a lot in advance!

**Comment by ilayn** [comment]
If you have Slycot installed you can use `AB13CD` routine or you can cook up your own version. It is not very difficult; here is a [starting point](https://github.com/ilayn/harold/blob/master/harold/_system_props.py#L83-L148)

**Comment by florentdimeglio** [comment]
Thanks!
