### ISSUE TITLE
t_eval is not respected for system with 0 states

### ISSUE THREAD

**Issue by hyumo** [python-control/python-control#742]
It seems that `t_eval` is ignored when simulating a system with `nstates=0`. 

The bug seems to be located at: https://github.com/python-control/python-control/blob/3b5f1990bf47180714423c420320f013bdd4dfaa/control/iosys.py#L1767-L1777

Instead, the following lines are expected to be used, I think: https://github.com/python-control/python-control/blob/3b5f1990bf47180714423c420320f013bdd4dfaa/control/iosys.py#L1798-L1825

**Comment by murrayrm** [comment]
Good catch @hyumo.  The first check for `nstates == 0` was redundant, so deleting it fixed the problem.  I also added some unit tests to catch this error.

This issue will close when #743 is merged.
