### ISSUE TITLE
sisotool - Show only rootlocus

### ISSUE THREAD

**Issue by egidioln** [python-control/python-control#744]
Hi all,

Is there a simple way to use ```matlab.sisotool``` but only get the Root locus plot? I think it is kind of annoying to have always all these other 3 plots if I am only interested in looking at the roots.
![image](https://user-images.githubusercontent.com/12188889/172576881-d45c7632-efb2-4109-b167-9c513758f181.png)

If not, I could implement this feature (maybe add a boolean variable to the kwargs?) if you think it's worth it...

Best,
Lucas

**Comment by sawyerbfuller** [comment]
hi @egidioln `sisotool` uses `root_locus` ([link](https://python-control.readthedocs.io/en/0.9.1/generated/control.root_locus.html#control.root_locus)) internally. Does just calling `root_locus(sys)` do what you need?
