### ISSUE TITLE
RTD Documentation defaults to v0.9.1 instead of v0.9.2

### ISSUE THREAD

**Issue by JBannwarth** [python-control/python-control#771]
The RTD documentation at https://python-control.readthedocs.io/ automatically redirects the user to the v0.9.1 documentation  at https://python-control.readthedocs.io/en/0.9.1/ instead of the latest version available. Is this expected behaviour?

Tested on Chrome/Edge/Safari and Windows 11/iOS 16.

**Comment by murrayrm** [comment]
Fixed (whoever released v0.9.2 didn't follow the [directions](https://github.com/python-control/python-control/wiki/Release-instructions)...).
