### ISSUE TITLE
Plot does not open on sisotool

### ISSUE THREAD

**Issue by danilofuchs** [python-control/python-control#783]
Sisotool does not open any plots

```python
import control.matlab
a = control.matlab.tf([1], [1, 2])
control.matlab.sisotool(a)
```

Environment:
- Python 3.10.2, 3.9.6
- python-control 0.9.2, 0.9.1, 0.9.0, 0.8.4
- Windows 10 20H2

**Comment by luizabheck** [comment]
I have the same problem

**Comment by bnavigator** [comment]
See #770

Your whole environment probably doesn't open any plots.

**Comment by danilofuchs** [comment]
Indeed, adding the following to the start of the file fixed it:

```python
import matplotlib.pyplot as plt
plt.ion()
```
