### ISSUE TITLE
tf2ss() does not seem to work for static gains

### ISSUE THREAD

**Issue by MauriceRienks** [python-control/python-control#81]
Creating a state space object of a static gain using tf2ss results in the ValueError: A must be square.

For example: tf2ss([1.],[1.])

**Comment by cwrowley** [comment]
I just verified this for `tf2ss` (using slycot)--definitely looks like a bug.  Note that there are two cases that may happen when you call `tf2ss`, depending on whether slycot is installed.  In fixing this bug, it would be good to add tests that test both versions (with and without slycot).

**Comment by slivingston** [comment]
The case of static gains when Slycot is installed is now handled, given changes from <https://github.com/python-control/Slycot/pull/5>, which will be in the next release of Slycot.

**Comment by slivingston** [comment]
fixed in PR #129, changes from which are now in `master` branch and will appear in the next release.
