### ISSUE TITLE
Incorrect nyquist plot

### ISSUE THREAD

**Issue by Avitan01** [python-control/python-control#830]
I'm using the control package with python 3.10 in Pycharm and Jupiter lab.
I have stumbled upon a possible issue while trying to create a Nyquist plot for a simple system
```
import control as ct

s = ct.tf('s'))
plant_1 = 1/(s*(s + 5)*(s + 7)))
ct.nyquist_plot(plant_1)

```

The result I'm getting is this: 

![download](https://user-images.githubusercontent.com/71692928/210130333-bafd7ce3-a131-4cc9-b54e-a9bf1d92af6e.png)

 While in MATLAB I'm getting different results

```
clear all;
close all;
clc;


s = tf('s');
plant_1 = 1/(s*(s + 5)*(s + 7));
nyquistplot(plant_1)

```
![image](https://user-images.githubusercontent.com/71692928/210130422-430d7e7f-9cc1-4f95-9ef0-0a9db3c00490.png)

**Is there a limitation that might be causing this issue or am I missing something?**

**Comment by bnavigator** [comment]
Look at the y-axis scale. The nyquist plot from control cuts off at `max_curve_magnitude` and scales the "infinity" loop for display within the plot boundaries.
https://python-control.readthedocs.io/en/0.9.2/generated/control.nyquist_plot.html#control.nyquist_plot

**Comment by henklaak** [comment]
Behaviour that will 'surprise' many, I guess. The documentation is not explicit about it and the default value of 20.

How about not drawing the large magnitudes at all? Just clip the traces at the limit with a ≫to indicate direction?

**Comment by murrayrm** [comment]
If you clip the traces, then it is harder to see the number of net encirclements. Especially if there is more than one.  For example
```
sys = ct.tf([1], [1, 3, 2]) * ct.tf([1], [1, 0, 1])
ct.nyquist_plot(sys)
```
which generates:
![multi-encirclement](https://user-images.githubusercontent.com/293362/216382912-16b6e496-b6d1-45b1-9731-d262589daf64.png)

**Comment by murrayrm** [comment]
We should definitely make sure all of this is well-documented, though.

**Comment by henklaak** [comment]
I'll take a stab at this, expect PR.
