### ISSUE TITLE
Calculate poles more smarter for state-space systems

### ISSUE THREAD

**Issue by cwrowley** [python-control/python-control#84]
As pointed out by @pmli in #27, the [current implementation](https://github.com/python-control/python-control/blob/0b26e062a6cd82da8a2420ebc3957e5267e6e116/control/statesp.py#L408) involves unnecessarily computing the characteristic polynomial, and then finding its roots.  This is inefficient and numerically unstable.  Much better to use `np.linalg.eigvals`.

**Comment by murrayrm** [comment]
Addressed in PR #91, now merged into master.
