### ISSUE TITLE
Optimal control example does not work on website or in examples folder.

### ISSUE THREAD

**Issue by drewhamiltonasdf** [python-control/python-control#851]
Using Jupyter with Python 3.8...

Plot at the end of the optimal steering example has a flatline output instead of the s curve shown on the site: https://python-control.readthedocs.io/en/latest/optimal.html#example

Example in example folder here similarly does not work.

**Comment by murrayrm** [comment]
What version of python-control are you running (check `control.__version__`)?  It should work on v0.9.3, but some earlier versions had problems converging (due to use of shooting instead of collocation).  Are you getting any warning messages?

**Comment by murrayrm** [comment]
This appears to be working in the current version of the toolbox.  Closing.
