### ISSUE TITLE
Problem with getting the zeros of the system

### ISSUE THREAD

**Issue by Betancourt20** [python-control/python-control#859]
Hi,

Thank you so much for the whole work you made already. It's really helpful.

I have a system with 3 inputs and 6 outputs. I'm trying to get the poles and zeros  but when I try to get the zeros I get the following error
```py
  1022 except ImportError:  # Slycot unavailable. Fall back to scipy.
   1023     if self.C.shape[0] != self.D.shape[1]:
-> 1024         raise NotImplementedError(
   1025             "StateSpace.zero only supports systems with the same "
   1026             "number of inputs as outputs.")
   1028     # This implements the QZ algorithm for finding transmission zeros
   1029     # from
   1030     # https://dspace.mit.edu/bitstream/handle/1721.1/841/P-0802-06587335.pdf.
   (...)
   1036     # The generalized eigenvalue problem is only solvable if its
   1037     # arguments are square matrices.
   1038     L = concatenate((concatenate((self.A, self.B), axis=1),
   1039                      concatenate((self.C, self.D), axis=1)), axis=0)

NotImplementedError: StateSpace.zero only supports systems with the same number of inputs as outputs.
```
On this case the matrices are wit the following dimension: ``` A(12 x 12), B(12x3), C(6x12), D(6x3) ```
any hint to solve this issue ?

Thanks in advance,
Julio

**Comment by murrayrm** [comment]
Computing the zeros of a non-square MIMO transfer function requires that you have Slycot installed.  More info on installation of Slycot in the [installation](https://python-control.readthedocs.io/en/0.9.3.post2/intro.html#installation) section of the documentation.
