### ISSUE TITLE
Travis CI build failing on master (problem with conda?)

### ISSUE THREAD

**Issue by murrayrm** [python-control/python-control#92]
The latest merges have caused Travis CI builds to fail:

[https://travis-ci.org/python-control/python-control](url)

The error is

`The command "conda update -q conda" failed and exited with 1 during . [sic]`

and the reason for this is

`FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text lib/libsqlite3.la'`

I'm installing conda on my local machine to see if I can replicate the error and figure out what is going on.  Hints are welcome.

**Comment by cwrowley** [comment]
I pushed a change to master that fixes this.
