### ISSUE TITLE
control.bode(Hz=True) the conversion is wrong.

### ISSUE THREAD

**Issue by fermvikt** [python-control/python-control#944]
Hi,

Version: control 0.9.4
\control\freqplot.py

Line 320:

                if Hz:
                    # omega_plot = omega_sys / (2. * math.pi)
                    omega_plot = omega_sys * (180 / (math.pi))

Line: 386

                    if Hz:
                        # Wcg, Wcp = Wcg/(2*math.pi), Wcp/(2*math.pi)
                        Wcg, Wcp = Wcg * (180 / (math.pi)), Wcp * (180 / (math.pi))

Best regards,
Vikt

**Comment by bnavigator** [comment]
The frequency is `f = 2*pi*omega` with `f` in `Hz` and `omega` in `rad/s` . These are not angles in degrees.

Side note: we work on code in the `main` branch, not in a released version.

**Comment by fermvikt** [comment]
Sorry,
Just for clarification.

                    Wcg, Wcp = Wcg/(2*math.pi), Wcp/(2*math.pi)

If this line is supposed to convert Wcg, Wcp from rad/s to Hz, I would do it by multiplying by (180/pi) and not by dividing by 2pi. 
Am I missing something here?

Best regards,
Viktor Ferm

**Comment by fermvikt** [comment]
Okay, thank you.
