### ISSUE TITLE
Gain margin is incorrect and does not match plot

### ISSUE THREAD

**Issue by elijahpettitt** [python-control/python-control#947]
The gain margin does not match the plot. I would put more helpful information but this is all I have. Sorry

```
import control as ctrl

v = ctrl.tf([1, .5, .05], [1, 0, 0, 0])

print(v)

mag, phase, omega = ctrl.bode_plot([v], dB=True, plot=True)
gm, pm, wcg, wcp = ctrl.margin(v)

print("gm, pm, wcg, wcp")
print(gm, pm, wcg, wcp)
```

### Output

```

s^2 + 0.5 s + 0.05
------------------
       s^3

gm, pm, wcg, wcp
0.09999999999999998 63.84244593481324 0.22360679774997896 1.0649862511565864
```

![image](https://github.com/python-control/python-control/assets/28421186/7aa20d57-2037-4291-ad0f-fa9a236c7165)

**Comment by roryyorke** [comment]
Thanks for the report.

With `ctrl.bode_plot(v, margins=True, dB=True);` you can get a visualization of the margins:

![image](https://github.com/python-control/python-control/assets/110974/ce530649-ef06-40e9-b5c6-abf1d06446b4)

`margin` returns the gain margin in "natural units"; convert your results to dB with `import numpy as np; 20 * np.log10(gm)` and you'll find the GM is -20dB.
