### ISSUE TITLE
plotting example mimo system

### ISSUE THREAD

**Issue by hariharan382** [python-control/python-control#959]
Hi All I am trying is to run the example mimo plotting in docs (0.9.4) , my version of the control pkg is 0.9.4, I could not plot the example code as below
```
sys1 = ct.tf([1], [1, 2, 1], name='sys1')
sys2 = ct.tf([1, 0.2], [1, 1, 3, 1, 1], name='sys2')
response = ct.frequency_response([sys1, sys2])

ct.bode_plot(response, initial_phase=0)
```
but getting error

`
File "C:\Users\user\OneDrive\Documents\2_dof_control_systems python\src\trial.py", line 21, in <module>
    ct.bode_plot(response, initial_phase=0)
  File "C:\Users\user\miniforge3\envs\control_env\Lib\site-packages\control\freqplot.py", line 214, in bode_plot
    omega, omega_range_given = _determine_omega_vector(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\miniforge3\envs\control_env\Lib\site-packages\control\freqplot.py", line 1593, in _determine_omega_vector
    omega_out = _default_frequency_range(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\miniforge3\envs\control_env\Lib\site-packages\control\freqplot.py", line 1666, in _default_frequency_range
    if sys.isctime():
       ^^^^^^^^^^^
AttributeError: 'TimeResponseData' object has no attribute 'isctime'
`

I could not plot any example as mention in docs below
[https://python-control.readthedocs.io/en/latest/plotting.html#response-functions](url)

some times, it complains omega is required from frequency_response, but in "frequency_response" method omega is optional , I don't where is the problem

**Comment by murrayrm** [comment]
A couple of issues:

* The documentation you are looking at is for the `latest`, which is the main development branch.  That version of python-control has significant changes to the various plotting routes (see #917 and the PR's linked there).  For version 0.9.4, you want to use https://python-control.readthedocs.io/en/0.9.4 (the specific section you address is not there).
* For version 0.9.4 of python-control, the `frequency_response` function requires `omega`; see [0.9.4 documentation](https://python-control.readthedocs.io/en/0.9.4/generated/control.frequency_response.html#control.frequency_response).

Ways to fix the problem:
* If you want to stick with version 0.9.4, you can generate a bode plot using `bode_plot([sys1, sys2])`.
* If you want to use the update _response/_plot pattern, checkout the main branch on GitHub.
