### ISSUE TITLE
documentation out of date

### ISSUE THREAD

**Issue by ShaneKosieradzki** [python-control/python-control#975]
I am looking at the [Plotting Data](https://python-control.readthedocs.io/en/latest/plotting.html) page of the docs and have spent some time trying to find the `root_locus_plot` function. But it does not seem to exist anywhere in the library.

**Comment by murrayrm** [comment]
Make sure that the version of python-control you are running and the documentation version match.  The link above points to the 'latest' version of python-control, which is the main (development) branch on GitHub.  If you installed python-control using pip or conda, you are probably running version 0.9.4, which is documented [here](https://python-control.readthedocs.io/en/0.9.4/).

The `root_locus_plot` command does not exist in the latest official release (0.9.4).  It is only in the development version (which you would need to install via GitHub).
