### ISSUE TITLE
Wrong parameter name in documentation

### ISSUE THREAD

**Issue by Davide-sd** [python-control/python-control#987]
I'm adapting my codes to `control 0.10.0`. In particular I'm switching from `ct.root_locus` to `ct.root_locus_map` in order to compute the root locus data. An error was raised in one of my tests, which led me to discover this. The documentation associated to `root_locus_map` is:

```py
def root_locus_map(sysdata, gains=None):
    """Compute the root locus map for an LTI system.

    Calculate the root locus by finding the roots of 1 + k * G(s) where G
    is a linear system with transfer function num(s)/den(s) and each k is
    an element of kvect.

    Parameters
    ----------
    sys : LTI system or list of LTI systems
        Linear input/output systems (SISO only, for now).
    kvect : array_like, optional
        Gains to use in computing plot of closed-loop poles.
    ...
    """
```

Note that (the new) `gains` is used as a function parameter, but `kvect` is documented (the old parameter from `ct.root_locus`).

**Comment by bnavigator** [comment]
Thanks! I made a small PR in #988. If there is more, please tell us or create your own PR!
